FROM nvidia/cuda:9.1-cudnn7-devel

MAINTAINER Keith McClellan <keith.mcclellan@mesosphere.com>

ARG CONDA_DIR="/home/conda/conda"
ARG CONDA_GID="100"
ARG CONDA_INSTALLER="Miniconda3-latest-Linux-x86_64.sh"
ARG CONDA_UID="1000"
ARG CONDA_URL="https://repo.continuum.io/miniconda"
ARG CONDA_USER="conda"
ARG CONDA_USER_HOME="/home/conda"
ARG DEBIAN_FRONTEND="noninteractive"
ARG TINI_URL="https://github.com/krallin/tini/releases/download"
ARG TINI_VERSION="v0.16.1"

ENV CONDA_DIR=${CONDA_DIR:-"/home/conda/conda"} \
    CONDA_USER=${CONDA_USER:-"conda"} \
    CONDA_USER_HOME=${CONDA_USER_HOME:-"/home/conda"} \
    DISTRO=${DISTRO:-"ubuntu"} \
    LANG="en_US.UTF-8" \
    LANGUAGE="en_US.UTF-8" \
    LC_ALL="en_US.UTF-8" \
    SHELL="/bin/bash"


RUN apt-get update -yq --fix-missing \
    && apt-get install -yq --no-install-recommends locales \
    && echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen \
    && locale-gen \
    && apt-get install -yq --no-install-recommends apt-utils \
    && apt-get -yq dist-upgrade \
    && apt-get install -yq --no-install-recommends \
       bash-completion \
       bzip2 \
       ca-certificates \
       curl \
       dirmngr \
       fonts-dejavu \
       fonts-liberation \
       git \
       gnupg \
       jq \
       openssh-client \
       sudo \
       unzip \
       vim \
       wget \
    && apt-get clean \
    && rm -rf /var/apt/lists/*

RUN cd /tmp \
    && curl --retry 3 -fsSL "$TINI_URL/$TINI_VERSION/tini" -o /usr/bin/tini \
    && curl --retry 3 -fsSL -O "$TINI_URL/$TINI_VERSION/tini.asc" \
    && export GNUPGHOME="$(mktemp -d)" \
    && rm -rf "$GNUPGHOME" tini.asc \
    && chmod +x /usr/bin/tini \
    && rm -rf /tmp/* \
    && useradd -m -N -u "$CONDA_UID" -g "$CONDA_GID" -s /bin/bash "$CONDA_USER"

USER ${CONDA_USER}
RUN cd "$CONDA_USER_HOME" \
    && curl --retry 3 -fsSL -O "$CONDA_URL/$CONDA_INSTALLER" \
    && bash "./$CONDA_INSTALLER" -b -p "$CONDA_USER_HOME/conda" \
    && rm -f "$CONDA_INSTALLER" \
    && $CONDA_DIR/bin/conda config --system --prepend channels conda-forge \
    && $CONDA_DIR/bin/conda config --system --set auto_update_conda false \
    && $CONDA_DIR/bin/conda config --system --set show_channel_urls true \
    && $CONDA_DIR/bin/conda clean -tipsy \
    && mkdir -p "$CONDA_USER_HOME/bin" \
    && mkdir -p "$CONDA_USER_HOME/work" \
    && mkdir -p "$CONDA_USER_HOME/.jupyter"
ENV PATH=$CONDA_DIR/bin:$PATH \
    HOME=$CONDA_USER_HOME

WORKDIR "$CONDA_USER_HOME/work"
ENTRYPOINT ["tini", "--"]
CMD ["conda.sh"]

# Add local files as late as possible to stay cache friendly
COPY --chown="1000:100" profile "$CONDA_USER_HOME/.profile"
COPY --chown="1000:100" bash_profile "$CONDA_USER_HOME/.bash_profile"
COPY --chown="1000:100" bashrc "$CONDA_USER_HOME/.bashrc"
COPY --chown="1000:100" dircolors "$CONDA_USER_HOME/.dircolors"
COPY --chown="1000:100" conda-home.sh /usr/local/bin/conda.sh
